@extends('backend.partial.adminMaster')

@section('contents')

<h2 class="mt-3 text-center text-decoration-underline">Salary Manage</h2>

@if ($errors->any())
  @foreach ($errors->all() as $error)
      <div class="alert alert-danger d-flex justify-content-between">{{$error}}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

      </div>
  @endforeach
@endif

 <!-- Button trigger modal -->
 <button type="button" class="btn btn-primary mb-1 mt-3 mx-3" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Add Salary
  </button>

  @if(session()->has('success'))

  <div class="alert alert-success mt-4 d-flex justify-content-between">
        {{session()->get('success')}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

  </div>
  @endif
  @if(session()->has('error'))

  <div class="alert alert-danger mt-4 d-flex justify-content-between">
        {{session()->get('error')}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

  </div>
  @endif




  <div style="overflow-x:auto;">

<table class="table my-4 rounded shadow table-bordered" style="margin-right: 200px;">
    <thead>
      <tr>
        <th class="py-4" scope="col">#</th>
        <th class="py-4" scope="col">Employee Name</th>
        <th class="py-4" scope="col">Employment Type</th>
        <th class="py-4" scope="col">Amount</th>
        <th class="py-4" scope="col">Month</th>
        <th class="py-4" scope="col">Bonus</th>

      </tr>
    </thead>
    <tbody>
         @foreach($salaries as $key=>$request)

        <tr>
            <th scope="row">{{$key+1}}</th>
            <td>{{$request->employee->name}}</td>
            <td>{{$request->employment}}</td>
            <td>{{$request->amount}}</td>
            <td>{{$request->month}}</td>
            <td>{{$request->bonus}}</td>

        </tr>
        @endforeach
        </tbody>

  </table>
  </div>


  {{$salaries->links()}}







  <!-- Modal -->
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <div>
            <h5 class="modal-title " id="staticBackdropLabel">Add Salary</h5>
          </div>
          <div>
            <p>Salary amount is automated generated by system </p>
          </div>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <form method="post" action="{{route('salaryCreate')}}">

            @csrf
        <div class="modal-body">
            <div class="form-group">
                <label for="exampleInputDepartment" >Employee Name</label>
                <select class="form-select" name="employee_id" required>
                    <option selected>Select Employee</option>
                    @foreach ($employee as $request)
                        <option value="{{ $request->user_id }}" >{{ $request->employeeDetail->name }} </option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="exampleInputDepartment">Employment Type</label>
                <select class="form-select" name="employment" required>
                    <option selected>Select type</option>
                    <option >Half-Time</option>
                    <option >Full-Time</option>

                </select>

            </div>
            {{-- <div class="form-group">
                <label for="exampleInputDesignation">Designation</label>
                <input name="designation" type="text" class="form-control" id="exampleInputDesignation" placeholder="Enter Designation">

            </div> --}}

            <div class="form-group">
                <label for="exampleInputPhone">Month</label>
                <input name="month" type="month" class="form-control" id="exampleInputPhone" required>

            </div>
            <div class="form-group">
                <label for="exampleInputPhone">Bonus</label>
                <input name="bonus" type="decimal" class="form-control" id="exampleInputPhone" placeholder="Enter Bonus Amount">

            </div>
        </div>
        <div class="modal-footer">
          {{-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> --}}
          <button type="submit" class="btn btn-primary" style="margin-right: 220px;" onclick="return confirm('Are you sure you want to add this salary?')">Add</button>
        </div>

    </form>

      </div>
    </div>
  </div>



@endsection
